export const TRANSFER_NFT_QUEUE_NAME = 'TRANSFER_NFT_QUEUE_NAME';
export const TRANSFER_NFT_QUEUE = 'TRANSFER_NFT_QUEUE';

export const CREATE_FORTRESS_WALLET_QUEUE_NAME = 'CREATE_FORTRESS_WALLET_QUEUE_NAME';
export const CREATE_FORTRESS_WALLET_QUEUE = 'CREATE_FORTRESS_WALLET_QUEUE';

export const CREATE_CIRCLE_WALLET_QUEUE_NAME = 'CREATE_CIRCLE_WALLET_QUEUE_NAME';
export const CREATE_CIRCLE_WALLET_QUEUE = 'CREATE_CIRCLE_WALLET_QUEUE';

export const CRAWL_NFT_QUEUE_NAME = 'CRAWL_NFT_QUEUE_NAME';

export const CRAWLER_EXCHANGE_SC_QUEUE_NAME = 'CRAWLER_EXCHANGE_SC_QUEUE_NAME';

export const CIRCLE_WEBHOOK_EVENT_QUEUE_NAME = 'CIRCLE_WEBHOOK_EVENT_QUEUE_NAME';

export const SETTLE_AUCTION_QUEUE_NAME = 'SETTLE_AUCTION_QUEUE_NAME';

export const FORTRESS_SEND_TX_QUEUE_NAME = 'FORTRESS_SEND_TX_QUEUE_NAME';

export const WITHDRAW_MONEY_FROM_FORTRESS_TO_CIRCLE_QUEUE_NAME = 'WITHDRAW_MONEY_FROM_FORTRESS_TO_CIRCLE_QUEUE_NAME';
